### ISSUE TITLE
лінкі ў футэры

### ISSUE THREAD

**Issue by foksia07** [diglabby/falanster2020#14]
вк: https://vk.com/falanster_by
фб: https://www.facebook.com/falanster.by/
інста: https://www.instagram.com/falanster.by/
ютуб: https://www.youtube.com/channel/UCAmTfxxasQwNaKkljnmvc5A

@fr0zen

**Comment by fr0zen** [comment]
@foksia07 зроблена

**Comment by foksia07** [comment]
@fr0zen ёў!
