### ISSUE TITLE
Замяніць фавіконку на блогу Фаланстэра

### ISSUE THREAD

**Issue by svetit** [diglabby/falanster2020#16]
https://blog.falanster.by/wp-admin/

Тут старая.

**Comment by svetit** [comment]
![logo_2018_f_trans_curves_w](https://user-images.githubusercontent.com/1722996/72660061-7e6d4c00-39d9-11ea-87c8-4bb922fd2991.png)

**Comment by svetit** [comment]
Тут белы лога на белым фоне.

**Comment by svetit** [comment]
@fr0zen @rizomaa Хто можа змяніць фавіконку ў блогу?

**Comment by svetit** [comment]
![logo_2018_f_trans_curves_wg](https://user-images.githubusercontent.com/1722996/72661060-25a4b000-39e7-11ea-8479-4a881a9157a9.png)
@fr0zen  Новая фавіконка.

**Comment by fr0zen** [comment]
@entropia тэст калі ласка

**Comment by svetit** [comment]
Гатова
