### ISSUE TITLE
[Тэставанне] У віджэце фб пры навядзенні на памаранчавыя надпісы, яны знікаюць

### ISSUE THREAD

**Issue by svetit** [diglabby/falanster2020#17]
Трэба паставіць іншы колер на навядзенне мышы на памаранчавыя надпісы. 
![Screenshot from 2020-01-18 10-23-14](https://user-images.githubusercontent.com/1722996/72660297-030d9980-39dd-11ea-961d-534fc2495eb4.png)

**Comment by fr0zen** [comment]
@svetit тэст калі ласка

**Comment by svetit** [comment]
Зараз добра. пры навядзенни - празрыста.
