### ISSUE TITLE
Стварыць тэставы асяродак

### ISSUE THREAD

**Issue by fr0zen** [diglabby/falanster2020#2]
- [x] 1. Стварыць дамен на Драніку праз Весту. 15 хв
- [x] 2. Усталяваць Новы Вордпрэсс. 15 хв
- [x] 3. Разаслаць дасягі да Вордпрэсса. 20 хв
- [x] 4. Зрабіць тэчку з тэмай рэпазіторыей git. 20 хв 
- [x] 5. Заліць на гітхаб тэму. 15 хв
- [x] 6. Дадаць усім правы на пуш. 15 хв
- [x] 7. Вызначыцца што выкарыстоўваем для аўтаматызацыі дженкінс або трэвіс. 15 хв
- [x] 8. Стварыць джобу на дженкінсе/трэвісе для пераноса зменаў з гітхаба на дамен. 20 хв

**Comment by rizomaa** [comment]
@fr0zen што тут яшчэ вісіць?

**Comment by rizomaa** [comment]
@fr0zen завяршы калі ласка яе бо вы глядае дзіўна, калі мы заканчваем рабіць працу, а тэставы асяродак не закончаны
