### ISSUE TITLE
Змяніць урл унутранай старонкі

### ISSUE THREAD

**Issue by svetit** [diglabby/falanster2020#23]
Зараз урл старонкі Супольнасць выглядае так http://dev.falanster.by/?page_id=35
А было б добра, каб выглядаў http://dev.falanster.by/supolnast , напрыклад.

Як гэта памяняць @rizomaa @fr0zen ? Мы глядзели з @foksia07 налады старонкі і не знайшлі.

**Comment by fr0zen** [comment]
@svetit @foksia07 як такі варыянт? :sun_with_face: :fox_face:

**Comment by foksia07** [comment]
@fr0zen выглядае найцудоўнейша, дзякуй! :)
