### ISSUE TITLE
Выраўняць каментары disqus па шырыні тэкста блога

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#28]

**Comment by rizomaa** [comment]
Харошая каманда grep -r -n "template-tags.php" --exclude="*.po"

тут крыніца https://stackoverflow.com/a/221929

правіць стылі 
https://blog.falanster.by/wp-admin/theme-editor.php?file=style.css&theme=readit_pro

**Comment by rizomaa** [comment]
@svetit правер калі ласка 
https://blog.falanster.by/2019/12/18/sustrjecha-padzjaka-ad-mapy-za-trashnjaga-dnja/

**Comment by rizomaa** [comment]
і буду зачыняць

**Comment by svetit** [comment]
@rizomaa  выглядае добра.
Але не падаецца, што усе каментары у блогу сцертыя. Я не магу знайсци ниводнага у старых запісах.

**Comment by rizomaa** [comment]
@svetit ты памятаеш, нейкія дакладныя запісы, дзе былі каментары?

я заўтра магу паглядзець, можа трэба пераналадзіць віджэт

**Comment by svetit** [comment]
https://blog.falanster.by/2019/05/20/kinabunker-5-2-jakim-budze-lichbavae-kahanne/

https://blog.falanster.by/2018/09/08/font-awesome-or-the-europe-ends/

@rizomaa на гэтых, на колькі я памятаю.

**Comment by rizomaa** [comment]
@svetit дзякуй. буду разбірацца

**Comment by rizomaa** [comment]
@svetit Твой запыт буду вырашыць https://github.com/diglabby/falanster2020/issues/48
