### ISSUE TITLE
Тэставанне (візуал + спасылкі). ФФ, хром (апошнія)

### ISSUE THREAD

**Issue by svetit** [diglabby/falanster2020#3]
- [x] Галоўная

- [x] Супольнасць

- [x] Кантакты

- [x] Блог

- [x] Падтрымаць

- [x] Праекты

- [x] Правілы сайта

**Comment by rizomaa** [comment]
@svetit разбей кали ласка гэту задачу, бо яна амаль ничога не кажа, што зараз фактычна робіш. гэту чачыняем. ствараць тэсты на кожную старонку асобна, або тут чэк ліст

**Comment by svetit** [comment]
@rizomaa  Разбіла!

**Comment by rizomaa** [comment]
> @rizomaa Разбіла!

@svetit стала больш сэнсу для тваёй працы?

**Comment by svetit** [comment]
@rizomaa  Так. заўтра будзе кантрольная праверка :)

**Comment by svetit** [comment]
Усе пратэставана разам з Юляй!
