### ISSUE TITLE
Усталяваць open graph пашырэнне для блога и сайта

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#34]
- [ ] Блог
- [ ] Сайт

Варыянты хуткага пошуку:
1. https://wordpress.org/plugins/wp-open-graph/
2. https://wordpress.org/plugins/og/
карацей их навалам, можна глядзець праз панэль вордпрэс маркета

Тут можна самім на каленцы напісаць:
https://www.elegantthemes.com/blog/tips-tricks/how-to-add-open-graph-tags-to-wordpress

**Comment by fr0zen** [comment]
@rizomaa усталяваў yoast на falanster.by. ён утрымлівае ў сабе і тулзы для опенграф

**Comment by rizomaa** [comment]
@fr0zen добра, я тады зачыняю гэту картку, таму, што задача гатова. дзякуй
