### ISSUE TITLE
Знайсці плагіны для сео

### ISSUE THREAD

**Issue by fr0zen** [diglabby/falanster2020#37]
- [x] для ключавікоў
- [x] для опенграфа

**Comment by fr0zen** [comment]
Усталявана

**Comment by rizomaa** [comment]
@fr0zen можаш звярнуць увагу на https://github.com/diglabby/falanster2020/issues/34
яна была створана раней за тваю картку і перасякаецца з пунктам гэтай задач. Пракаментуй калі ласка.

**Comment by fr0zen** [comment]
@rizomaa адказаў у #34 . гэту таску лічу завершанай.
