### ISSUE TITLE
Зрабіць верстку старонак

### ISSUE THREAD

**Issue by fr0zen** [diglabby/falanster2020#4]
- [x] 1. Галоўная старонка (10 гадзін)
  - [x] а. стварэнне HTML структуры
  - [x] б. стварэнне стыляў (паглядзець, якія стылі можна выкарыстоўваць паўторна)
- [x] 2. Старонка кантактаў па шаблону галоўнай. (3 гадзіны)
  - [x] а. стварэнне HTML структуры 
  - [x] б. стварэнне стыляў (паглядзець, якія стылі можна выкарыстоўваць паўторна)
- [x] 3. Старонка праектаў. (3 гадзіны)
  - [x] а. стварэнне HTML структуры
  - [x] б. стварэнне стыляў (паглядзець, якія стылі можна выкарыстоўваць паўторна)
- [x] 4. Старонка супольнасці (4 гадзіны)
  - [x] а. стварэнне HTML структуры 
  - [x] б. стварэнне стыляў (паглядзець, якія стылі можна выкарыстоўваць паўторна)

**Comment by rizomaa** [comment]
@foksia07 абнави кали ласка тут інфу.

**Comment by foksia07** [comment]
@rizomaa абнавіла!)
