### ISSUE TITLE
Палешшыць навігацыю прыціска "Падтрымаць"

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#40]
Заўвагі

- [x] 1. Наладзіць, каб ён вёў на поле даната адразу праз айдзішнік, кшталту https://dev.falanster.by/padtrymacz#doika
- [x] 2. У меню і на верхняй панэлі яно розных колераз (аранжавы і зялёны). Так мусіць быць?

**Comment by svetit** [comment]
2. Так. Асобны колер у меню для "Падтрымаць" - гэта фіча, каб выдзяліць візуальна у меню.
Бо на мабілцы кнопка "Падтрымаць" знікае.

**Comment by fr0zen** [comment]
Зроблена
