### ISSUE TITLE
Палепшыць старонку "Кантакты"

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#41]
- [x] 1. Як пісаць "Адрэс ці адрас"?
- [x] 2. Зрабіць мэйл і тэлефон клікабельнымі. Гэтапалепшыць мабільную навігацыю.
- [x] 3. @fr0zen гэта виджэт, які робіцца нашым модулем на мапе?

пазырце калі ласка разам @svetit @foksia07

**Comment by svetit** [comment]
1. Адрас. Зменім
2.Зробім.

**Comment by svetit** [comment]
1. Адрас зменены.
2. Мейл і тэлефон клікабельныя. 
Яны спрацоўваюць у Юлі з мабілы.
 але у мяне не спрацоўваюць, пэўна, таму што я там доступы закрыла браўзера да мейла і тэлефона.

**Comment by fr0zen** [comment]
@rizomaa, так, можна забраць на мапе з дапамогай нашага модулю
