### ISSUE TITLE
Палепшыць старонку "Супольнасць"

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#43]
- [x] 1. Зрабіць каб анкета "Стаць валанцёрам!" адчынялася у новай укладцы.
- [x] 2. Змяніць адваротны лінк у апісанні анкеты на актуальны: https://docs.google.com/forms/d/e/1FAIpQLSf78xrCLn3zsUaXmQGNrA58puu1Mk7AK4gIFyAwVXpNU1TyAw/viewform
- [x] 3. Ці не думалі зрабіць нейкі эфект, калі падводзіш мышку на стаць валанцёрам вялікую плошчу?
- [x] 4. Ці будзе неякая значка да gpg ключоў удзельнікаў каманды? @svetit

**Comment by foksia07** [comment]
1 пункт выправіла.

**Comment by svetit** [comment]
gpg лагатып дадала1
