### ISSUE TITLE
Палепшыць Галоўную старонку

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#44]
- [x] 1. Калі падводзіш мышку на прыціск "Пра нас", там яшчэ старая спасылка, ці патрэбна так?
- [x] 2. Прыбраць апошнюю z у шляху на старонку супольнасці https://dev.falanster.by/supolnascz/
- [x] 3. Ці ёсць інструкцыя, як дадаваць праект на галоўную? @foksia07 і прыбіраць?
- [x] 4. Прыбраць апошнюю z у шляху на старонку "Падтрымаць" https://dev.falanster.by/padtrymacz/

**Comment by foksia07** [comment]
1 і 3 - вырашаныя.

**Comment by svetit** [comment]
Усе вырашаны!
