### ISSUE TITLE
Не працуе сайт Градкі: cc.falanster.by

### ISSUE THREAD

**Issue by svetit** [diglabby/falanster2020#45]
Не працуе сайт cc.falanster.by
Раней ен перанакіроўваўся на falanster.by@gmail.com
І цяпер перанакіраванне засталося.

Правільна я разумею, што яго няма на гэтым дамене. Ен быў убудаваны у друпал?
І трэба яго разгарнуць.

**Comment by fr0zen** [comment]
Так, быў старонкай друпала падаецца. Ці быў на old ён, магчыма ведаеш?

**Comment by rizomaa** [comment]
Вось гэта старонка
cc.falanster.by
 і гэта
creativecommons.by
вядуць сюды 
->
https://falanster.by/be/creativecommons

а патрэбна, каб сюды:
https://old.falanster.by/be/creativecommons

**Comment by svetit** [comment]
Знайшла сайт па лінку https://old.falanster.by/be/creativecommons

Пакуль можна яго выкарыстоўваць.

**Comment by rizomaa** [comment]
@svetit Выправіў
Праверыў. Працуе.

1. пачысці кэш
2. запускай cc.falanster.by  і creativecommons.by

**Comment by svetit** [comment]
Код градкі ляжыць тут https://github.com/TastyCreativity/gradka

**Comment by rizomaa** [comment]
пакуль зачыняю задачу, бо перанос лэндынга на новы паддамем гэта асобная задача. магу табе паказаць як робицца @svetit
