### ISSUE TITLE
Зрабіць рэзерваванне сайта Фаланстэра на old.falanster.by

### ISSUE THREAD

**Issue by rizomaa** [diglabby/falanster2020#8]
- [x] з falanster.by на old.falanster.by
- [x] праверыць, як выводзяцца фоты
- [x] праверыць спасылкі

Што зрабіць:

- [x] Скапіраваць базу і код на новае месца.
- [x] Запусціць скрыпты для праўкі.
- [x] Праверыць, ці усё схапілася.
- [ ] праверыць спасылкі у summary (падсумавання)

**Comment by rizomaa** [comment]
75% задачы зроблена аўтаматычна.

Засталося 42 вузла ў падсумаванні змяніць (ручкамі.)

Тут панэль працы:
https://old.falanster.by/be/admin/content/scanner

у пошук (Step 1: Search for) набіраю http://falanster.by/
змяніць (Step 2: Replace with) на https://old.falanster.by/

**Comment by rizomaa** [comment]
@svetit папрашу тваю дапамогу на гэтую працу.

**Comment by svetit** [comment]
@rizomaa  гатова!

**Comment by rizomaa** [comment]
@svetit дзякуй
